### ISSUE TITLE
psort for files with over 10k columns

### ISSUE THREAD

**Issue by Kailewang** [ruanjue/psort#1]
Hi,
Try to sort my single cell RNA matrix file, which contains over 10k columns, I got only 1 column after sorting...not sure why..., meanwhile, I tested psort with other files, which has less 1k columns, it works great.

**Comment by ruanjue** [comment]
Hi, Kaile

Could you describe it more? Like this
```sh
A1  B1  C1  D1  E1  D1 ...
A2  B2  C2  D2  E2  D2 ...
```
after psort the column A
```sh
A1
A2
```
I think you didn't mean it, but please describe it as the above.

Jue

**Comment by ruanjue** [comment]
I had add a compile option to Makefile. `make UFLAGS="-DLONG_ROW"` to make it support <= 16 M byte rows.

**Comment by Kailewang** [comment]
Thanks Dr. ruan, use updated version psort, problem solved.
